=== skroflin/faks/skroflin-označiteljski/vježba9/catalog_kroflin/catalog.dtd
<!ELEMENT catalog (book+)>
<!ELEMENT book (title,author,category,rating)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT rating (#PCDATA)>

=== skroflin/faks/skroflin-označiteljski/vježba9/catalog_kroflin/catalog_kroflin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "catalog.dtd">
<catalog>
    <book>
        <title>
            Odiseja u svemiru 2001.
        </title>

        <author>
            Arthur C. Clarke
        </author>

        <category>
            Fantasy
        </category>

        <rating>
            5
        </rating>
    </book>

    <book>
        <title>
            Das Kapital
        </title>

        <author>
            Karl Marx
        </author>

        <category>
            Philosophy
        </category>
        
        <rating>
            1
        </rating>
    </book>

    <book>
        <title>
            The Plague
        </title>

        <author>
            Albert Camus
        </author>

        <category>
            Novel
        </category>
        
        <rating>
            5
        </rating>
    </book>
</catalog>
