=== skroflin/faks/skroflin-označiteljski/vježba9/catalog_kroflin2/catalog_kroflin.dtd
<!ELEMENT katalog (knjiga+)>
<!ELEMENT knjiga (naslov,autor,vrsta,ocjena,čitatelj*,objavljena?,godina_kataloga)>
<!ELEMENT naslov (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT vrsta (#PCDATA)>
<!ELEMENT ocjena (#PCDATA)>
<!ELEMENT čitatelj (#PCDATA)>
<!ELEMENT objavljena (#PCDATA)>
<!ELEMENT godina_kataloga (#PCDATA)>
<!ATTLIST vrsta žanr (fantasy | classic | biography) #REQUIRED>
<!ATTLIST ocjena broj (1|2|3|4|5) "5">
<!ENTITY godina "Katalog SK, 2022">

=== skroflin/faks/skroflin-označiteljski/vježba9/catalog_kroflin2/catalog_kroflin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE katalog SYSTEM "catalog_kroflin.dtd">
<katalog>
    <knjiga>
        <naslov>Odiseja u svemiru 2001.</naslov>
        <autor>Arthur C. Clarke</autor>
        <vrsta žanr="fantasy"/>
        <ocjena broj="5"/>
        <čitatelj>Sven Kroflin</čitatelj>
        <čitatelj>Pero Perić</čitatelj>
        <objavljena></objavljena>
        <godina_kataloga>&godina;</godina_kataloga>
    </knjiga>
    <knjiga>
        <naslov>Gospodari Prstenova</naslov>
        <autor>J. R. R. Tolkien</autor>
        <vrsta žanr="fantasy"/>
        <ocjena broj="5"/>
        <čitatelj>Fran Kroflin</čitatelj>
        <čitatelj>Ivan Ivić</čitatelj>
        <godina_kataloga>&godina;</godina_kataloga>
    </knjiga>
    <knjiga>
        <naslov>Harry Potter</naslov>
        <autor>J. K. Rowling</autor>
        <vrsta žanr="fantasy"/>
        <ocjena broj="5"/>
        <čitatelj>Matej Kroflin</čitatelj>
        <godina_kataloga>&godina;</godina_kataloga>
    </knjiga>
</katalog>
