=== skroflin/faks/Praktični rad 2/zadatakXML_kroflin.dtd
<!ELEMENT korisnik_knjižnice (korisnik+)>
<!ELEMENT korisnik (ime_prezime,ulica,mjesto_prebivališta,datum_rođenja*,zanimanje?,tekst)>
<!ELEMENT ime_prezime (#PCDATA)>
<!ELEMENT ulica (#PCDATA)>
<!ELEMENT mjesto_prebivališta EMPTY>
<!ATTLIST mjesto_prebivališta grad (Osijek|Vinkovci|Valpovo) #REQUIRED>
<!ELEMENT datum_rođenja (#PCDATA)>
<!ELEMENT zanimanje (#PCDATA)>
<!ELEMENT tekst (#PCDATA)>
<!ENTITY tekst "Popis korisnika knjižnice">

=== skroflin/faks/Praktični rad 2/zadatakXML_kroflin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE korisnik_knjižnice SYSTEM "zadatakXML_kroflin.dtd">
<korisnik_knjižnice>
    <korisnik>
        <ime_prezime>
            Mirjana Merdar
        </ime_prezime>
        <ulica>
            Kapucinska 5
        </ulica>
        <mjesto_prebivališta grad="Osijek"/>
        <datum_rođenja>20. travnja 1996.</datum_rođenja>
        <zanimanje>dipl ing. strojarstva</zanimanje>
        <tekst>&tekst;</tekst>
    </korisnik>
    <korisnik>
        <ime_prezime>
            Augustin Trepšić
        </ime_prezime>
        <ulica>
            Županijska 20
        </ulica>
        <mjesto_prebivališta grad="Vinkovci"/>
        <datum_rođenja>7. srpnja 1998.</datum_rođenja>
        <zanimanje>medicinski tehničar</zanimanje>
        <tekst>&tekst;</tekst>
    </korisnik>
    <korisnik>
        <ime_prezime>
            Žozefina Lukšić
        </ime_prezime>
        <ulica>
            Vukovarska 10
        </ulica>
        <mjesto_prebivališta grad="Osijek"/>
        <datum_rođenja>25. rujna 1998.</datum_rođenja>
        <zanimanje>prof hrvatskog jezika</zanimanje>
        <tekst>&tekst;</tekst>
    </korisnik>
    <korisnik>
        <ime_prezime>
            Ilko Strlec
        </ime_prezime>
        <ulica>
            Vukovarska 50
        </ulica>
        <mjesto_prebivališta grad="Valpovo"/>
        <datum_rođenja>1. prosinca 1996.</datum_rođenja>
        <zanimanje>zemljomjer</zanimanje>
        <tekst>&tekst;</tekst>
    </korisnik>
</korisnik_knjižnice>
