=== skroflin/faks/skroflin-označiteljski/vježba11/ponavljanje/popis_kroflin.dtd
<!ELEMENT popis (student+)>
<!ELEMENT student (ime, prezime, odsjek, studij, godina, zaključna_ocjena, ponavljačka_godina?)>
<!ELEMENT ime (#PCDATA)>
<!ELEMENT prezime (#PCDATA)>
<!ELEMENT odsjek (#PCDATA)>
<!ELEMENT studij (#PCDATA)>
<!ELEMENT godina (#PCDATA)>
<!ELEMENT zaključna_ocjena (#PCDATA)>
<!ELEMENT ponavljačka_godina (#PCDATA)>
<!ATTLIST odsjek naziv (OZIZ|germanistika|anglistika) "OZIZ">
<!ATTLIST zaključna_ocjena broj (1|2|3|4|5) "3">
<!ATTLIST ponavljačka godina (da|ne) #REQUIRED>

=== skroflin/faks/skroflin-označiteljski/vježba11/ponavljanje/popis_kroflin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE popis SYSTEM "popis_kroflin.dtd">
<popis>
    <student>
        <ime>Sven</ime>
        <prezime>Kroflin</prezime>
        <odsjek naziv="OZIZ"/>
        <studij>Informatologija</studij>
        <godina>Prva</godina>
        <zaključna_ocjena>3</zaključna_ocjena>
        <ponavljačka_godina>Ne</ponavljačka_godina>
    </student>
    <student>
        <ime>Stjepan</ime>
        <prezime>Šokčević</prezime>
        <odsjek naziv="OZIZ"/>
        <studij>Informatologija</studij>
        <godina>Prva</godina>
        <zaključna_ocjena>4</zaključna_ocjena>
        <ponavljačka_godina>Da</ponavljačka_godina>
    </student>
    <student>
        <ime>Lara</ime>
        <prezime>Barišić</prezime>
        <odsjek naziv="anglistika"/>
        <studij>Engleski i Njemački</studij>
        <godina>Prva</godina>
        <zaključna_ocjena>4</zaključna_ocjena>
        <ponavljačka_godina>Ne</ponavljačka_godina>
    </student>
</popis>
